Added Documentation for usage with async tools. Fixes #626
fastapi/sqlmodel pull request #633
Opened 2023-08-08 15:24 UTC by deshetti

I have spent a good amount of time to figure out async implementation with SQLModel & FastAPI in one of our projects and thought this would be a helpful guide for anyone who is looking to do the same in their projects.

A simple working project is available here to test. Running the docker-compose will start the postgres with the required database: https://github.com/deshetti/sqlmodel-async-example

2023-11-19 22:08 UTC, peidrao requested changes

2023-11-19 22:08 UTC, peidrao commented on docs/advanced/async-tools.md
> +```
```suggestion
```python
```

2023-11-19 22:08 UTC, peidrao commented on docs/advanced/async-tools.md
> +```
```suggestion
```bash
pip install sqlmodel asyncpg fastapi uvicorn
```
```

2023-11-29 17:43 UTC, alejandroperezlopez commented on docs/advanced/async-tools.md
> +# Ayschronous Context manager for handling database sessions
```suggestion
# Asynchronous Context manager for handling database sessions
```

2024-02-08 09:38 UTC, StashOfCode commented
Are we merging this in this century or next?

2024-04-10 21:39 UTC, moralespanitz commented
@tiangolo Why don't you add the contribution?

2024-07-11 10:50 UTC, vduseev commented
Interesting approach. Why not use `async_sessionmaker`?

2024-08-02 21:38 UTC, thomasborgen commented on docs/advanced/async-tools.md
> +    db_user = User(**user.dict())
`.dict()` is deprecated for `model_dump()` 

```suggestion
    db_user = User(**user.model_dump())
```

2024-08-02 21:38 UTC, thomasborgen commented on docs/advanced/async-tools.md
> +    db_user = User(**user.dict())
.dict() is deprecated for model_dump()
```suggestion
    db_user = User(**user.model_dump())
```

2024-08-02 21:38 UTC, thomasborgen commented on docs/advanced/async-tools.md
> +    return result
Maybe drop the `create_user()` function and just have everything in here. We also get the added benefit of showing of dependency injection, we are in the advanced section after all. 

```suggestion
@app.post("/users/", response_model=User)
async def create_user_endpoint(
    user: UserCreate,
    session: AsyncSession = Depends(get_session),
):
    db_user = User(user.model_dump())
    session.add(db_user)
    await session.commit()
    await session.refresh(db_user)
    return db_user
```

2024-12-05 06:30 UTC, zuoc1993 commented
When will this be released?

2024-12-22 05:28 UTC, grimzy commented on docs/advanced/async-tools.md
> +from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
Can use https://github.com/fastapi/sqlmodel/blob/0c65fed61b72c95fdf675c199c8bd45642122e1c/sqlmodel/ext/asyncio/session.py#L32 instead of SQLAlchemy's

2026-05-13 09:31 UTC, svlandeg reviewed
Hi @deshetti, all,

Thanks for the contribution 🙏 

We've discussed this internally and decided that we prefer to write the first draft of this new documentation section ourselves. We are now tracking this on our internal TODO list. We'll go ahead and close this one in the meantime.

2026-05-13 09:31 UTC, closed without merging