Added typecheck to sqlalchemy JSON
fastapi/sqlmodel pull request #931
Opened 2024-05-08 15:55 UTC by LucaGelmini

In sqlmodel/main.py there was missing a typecheck for the JSON type supported by sqlalchemy. So it was not possible to define a model with a JSON field.

2024-05-09 18:21 UTC, mmmcorpsvit commented
please add JSONB support too

2024-07-12 17:07 UTC, vduseev approved these changes
A single line change that is ready to be merged and doesn't require anything really.

2024-07-12 17:21 UTC, vduseev commented
Ah, never mind. Found a fix: 

```python
from sqlmodel import SQLModel, Field, JSON


class User(SQLModel, table=True):
    id: int = Field(..., primary_key=True)
    data: JSON = Field(default={}, sa_type=JSON)
```

2024-07-19 14:21 UTC, alessiamarcolini commented
Hi @vduseev @LucaGelmini is there an update on when this can be merged?

2024-07-19 14:37 UTC, LucaGelmini commented
As I see this can be merged right now. The JSON compatibility was supported by SQLAlchemy, just that it wasn't implemented inside the SQLModel map of the SQLAlchemy types. So, I just changed two lines to include the JSON class 😂. Very straightforward change.

2024-07-19 14:41 UTC, LucaGelmini commented
First collaboration in a repo though, so if I'm missing something please tell me 🫡

2024-07-29 18:04 UTC, LucaGelmini reviewed
not imported type

2024-07-29 18:04 UTC, LucaGelmini commented on sqlmodel/main.py
> +        return GUID
This type was not imported, is better to return sqlalchemy UUID type. That's why test are failing

2024-09-06 14:59 UTC, TimNekk commented
Really want this to be merged 🙏

2024-10-31 10:29 UTC, MRigal commented on sqlmodel/main.py
> +        return JSON
Don't you want `issubclass(type_, Mapping)` rather here?

Also it is probably not clear if JSON or JSONB is the desired type.

Maybe better to document the workaround in the docs

2025-08-22 15:57 UTC, YuriiMotov requested changes
@LucaGelmini, thanks for your interest!

Are you still ready to work on this?
We need to cover this by tests at least.
But I would actually extend this to also support `Sequence` and `Mapping`

2025-08-22 15:57 UTC, YuriiMotov commented on sqlmodel/main.py
> +        return JSON
Shouldn't it be `if issubclass(type_, pydantic.Json):` instead?
Or better
```py
    if issubclass(type_, (Sequence, Mapping, Json)):
        return JSON
```

2025-10-06 18:20 UTC, closed without merging

2025-10-08 09:20 UTC, YuriiMotov commented
Is anybody up to take this over?
We need to add tests